[build-system]
requires = ["setuptools==83.0.0", "wheel==0.47.0"]
build-backend = "setuptools.build_meta"

[project]
name = "nivrit-sdk"
version = "2.1.0"
description = "Nivrit secrets SDK for Python"
readme = "README.md"
requires-python = ">=3.10"
license = "AGPL-3.0-only"

[project.urls]
Repository = "https://github.com/infinio-labs/nivrit"

[tool.setuptools.packages.find]
where = ["."]
include = ["nivrit*"]

[tool.setuptools.package-data]
nivrit = ["bin/*"]
